/* الإسلام المفترى عليه — ISLAM FALSELY ACCUSED — app.js */
/* Based on "Al-Islam al-Muftara Alayh" by Sheikh Mohammed al-Ghazali (1917-1996) */

const T={ar:{appTitle:'الإسلام المفترى عليه',splashSub:'الرد على الافتراءات بالحجة والدليل',splashHint:'اضغط للتخطي',tabHome:'الرئيسية',tabCards:'البطاقات',tabDefense:'الدفاع',tabHabits:'العادات',tabQuiz:'اختبار',tabAbout:'الكتاب',cardsTitle:'الإسلام المفترى عليه',cardsDesc:'٢٠ تهمة باطلة ضد الإسلام مع الرد العلمي المفصّل',defenseTitle:'خط الدفاع',defenseDesc:'حجج وأدلة قوية للرد على الشبهات الشائعة',habitsTitle:'عاداتي اليومية',habitsDesc:'عادات للمدافع عن الإسلام',quizTitle:'اختبر معرفتك',quizDesc:'ما مدى قدرتك على الرد على الشبهات؟',helpTitle:'❓ مساعدة',duaPanelTitle:'🤲 أدعية',resetBtn:'إعادة تعيين',submitQuiz:'اعرف النتيجة',dailyLabel:'✨ حقيقة اليوم',quizAgain:'أعد الاختبار',share:'مشاركة',searchPlaceholder:'ابحث...',streakMsg:'يوم متتالي!',allDone:'أحسنت!',splashFeatures:['٢٠ تهمة والرد عليها','خط دفاع بالأدلة','عادات يومية للمدافع','اختبار معرفة + أدعية']},
en:{appTitle:'Islam Falsely Accused',splashSub:'Responding to false accusations with evidence',splashHint:'tap to skip',tabHome:'Home',tabCards:'Cards',tabDefense:'Defense',tabHabits:'Habits',tabQuiz:'Quiz',tabAbout:'Book',cardsTitle:'Islam Falsely Accused',cardsDesc:'20 false accusations against Islam with detailed scholarly responses',defenseTitle:'Line of Defense',defenseDesc:'Strong arguments and evidence to respond to common doubts',habitsTitle:'My Daily Habits',habitsDesc:'Habits for the defender of Islam',quizTitle:'Test Your Knowledge',quizDesc:'How well can you respond to misconceptions?',helpTitle:'❓ Help',duaPanelTitle:'🤲 Duas',resetBtn:'Reset Today',submitQuiz:'See Results',dailyLabel:'✨ Today\'s Truth',quizAgain:'Retake Quiz',share:'Share',searchPlaceholder:'Search...',streakMsg:'day streak!',allDone:'Well done!',splashFeatures:['20 accusations and their refutations','Defense line with evidence','Daily habits for defenders','Knowledge quiz + duas']},
fr:{appTitle:'L\'Islam Faussement Accus\u00e9',splashSub:'R\u00e9pondre aux fausses accusations avec des preuves',splashHint:'appuyez pour passer',tabHome:'Accueil',tabCards:'Cartes',tabDefense:'D\u00e9fense',tabHabits:'Habitudes',tabQuiz:'Quiz',tabAbout:'Livre',cardsTitle:'L\'Islam Faussement Accus\u00e9',cardsDesc:'20 fausses accusations contre l\'Islam avec des r\u00e9ponses d\u00e9taill\u00e9es',defenseTitle:'Ligne de D\u00e9fense',defenseDesc:'Arguments et preuves solides pour r\u00e9pondre aux doutes courants',habitsTitle:'Mes Habitudes',habitsDesc:'Habitudes pour le d\u00e9fenseur de l\'Islam',quizTitle:'Testez Vos Connaissances',quizDesc:'Pouvez-vous r\u00e9pondre aux id\u00e9es fausses ?',helpTitle:'❓ Aide',duaPanelTitle:'🤲 Duas',resetBtn:'R\u00e9initialiser',submitQuiz:'Voir les R\u00e9sultats',dailyLabel:'✨ V\u00e9rit\u00e9 du Jour',quizAgain:'Refaire',share:'Partager',searchPlaceholder:'Rechercher...',streakMsg:'jours cons\u00e9cutifs !',allDone:'Bravo !',splashFeatures:['20 accusations et r\u00e9futations','Ligne de d\u00e9fense avec preuves','Habitudes pour d\u00e9fenseurs','Quiz + duas']}};

const CARDS=[
{id:1,emoji:'⚔️',ar:{title:'الإسلام والعنف',desc:'يُتّهم الإسلام بالعنف والإرهاب. والحقيقة أن الإسلام دين السلام. القتال في الإسلام دفاعي فقط ومحكوم بقواعد صارمة تحمي المدنيين والأطفال والنساء وحتى الأشجار.',verse:'لَا إِكْرَاهَ فِي الدِّينِ',verseRef:'سورة البقرة ٢: ٢٥٦',action:'اقرأ عن أخلاق الحرب في الإسلام وقارنها بالحروب الحديثة'},en:{title:'Islam and Violence',desc:'Islam is accused of violence and terrorism. The truth is Islam is a religion of peace. Fighting is only defensive and governed by strict rules protecting civilians, children, women, and even trees.',verse:'There shall be no compulsion in religion',verseRef:'Surah Al-Baqarah 2:256',action:'Read about war ethics in Islam and compare with modern wars'},fr:{title:'L\'Islam et la Violence',desc:'L\'Islam est accus\u00e9 de violence et terrorisme. La v\u00e9rit\u00e9 est que l\'Islam est une religion de paix. Le combat est uniquement d\u00e9fensif.',verse:'Nulle contrainte en religion',verseRef:'Sourate Al-Baqarah 2:256',action:'Lisez les r\u00e8gles de guerre en Islam et comparez'}},
{id:2,emoji:'👩',ar:{title:'المرأة في الإسلام',desc:'يُزعم أن الإسلام يضطهد المرأة. والحقيقة أن الإسلام كرّم المرأة قبل الغرب بـ ١٤ قرناً: حق الميراث والتعليم والعمل والتملك.',verse:'وَلَهُنَّ مِثْلُ الَّذِي عَلَيْهِنَّ بِالْمَعْرُوفِ',verseRef:'سورة البقرة ٢: ٢٢٨',action:'تعرّف على حقوق المرأة التي كفلها الإسلام قبل ١٤٠٠ سنة'},en:{title:'Women in Islam',desc:'It is claimed Islam oppresses women. The truth is Islam honored women 14 centuries before the West: rights to inheritance, education, work, and property ownership.',verse:'And women have rights similar to those held over them in kindness',verseRef:'Surah Al-Baqarah 2:228',action:'Learn about women\'s rights Islam guaranteed 1400 years ago'},fr:{title:'La Femme en Islam',desc:'On pr\u00e9tend que l\'Islam opprime les femmes. La v\u00e9rit\u00e9 est que l\'Islam a honor\u00e9 les femmes 14 si\u00e8cles avant l\'Occident.',verse:'Elles ont des droits \u00e9quivalents \u00e0 leurs obligations',verseRef:'Sourate Al-Baqarah 2:228',action:'D\u00e9couvrez les droits des femmes garantis par l\'Islam il y a 1400 ans'}},
{id:3,emoji:'🔬',ar:{title:'الإسلام والعلم',desc:'يُقال إن الإسلام ضد العلم والتقدم. والحقيقة أن الحضارة الإسلامية قادت العالم علمياً لقرون وأسست لعلوم الجبر والكيمياء والطب.',verse:'هَلْ يَسْتَوِي الَّذِينَ يَعْلَمُونَ وَالَّذِينَ لَا يَعْلَمُونَ',verseRef:'سورة الزمر ٣٩: ٩',action:'ابحث عن عالم مسلم واقرأ إنجازاته'},en:{title:'Islam and Science',desc:'It is said Islam is against science and progress. The truth is Islamic civilization led the world scientifically for centuries, founding algebra, chemistry, and medicine.',verse:'Are those who know equal to those who do not know?',verseRef:'Surah Az-Zumar 39:9',action:'Research a Muslim scientist and read their achievements'},fr:{title:'L\'Islam et la Science',desc:'On dit que l\'Islam est contre la science. La v\u00e9rit\u00e9 est que la civilisation islamique a men\u00e9 le monde scientifiquement pendant des si\u00e8cles.',verse:'Sont-ils \u00e9gaux, ceux qui savent et ceux qui ne savent pas ?',verseRef:'Sourate Az-Zumar 39:9',action:'Recherchez un savant musulman et lisez ses r\u00e9alisations'}},
{id:4,emoji:'🗽',ar:{title:'الإسلام والحرية',desc:'يُتّهم الإسلام بقمع الحريات. والحقيقة أن الإسلام كفل حرية العقيدة والرأي والتفكير، وحرّم الإكراه على الدين.',verse:'وَقُلِ الْحَقُّ مِن رَّبِّكُمْ فَمَن شَاءَ فَلْيُؤْمِن وَمَن شَاءَ فَلْيَكْفُرْ',verseRef:'سورة الكهف ١٨: ٢٩',action:'اقرأ عن ميثاق المدينة الذي ضمن حرية العقيدة لغير المسلمين'},en:{title:'Islam and Freedom',desc:'Islam is accused of suppressing freedoms. The truth is Islam guaranteed freedom of belief, opinion, and thought, and forbade religious coercion.',verse:'The truth is from your Lord. Whoever wills, let them believe; whoever wills, let them disbelieve',verseRef:'Surah Al-Kahf 18:29',action:'Read about the Medina Charter that guaranteed freedom for non-Muslims'},fr:{title:'L\'Islam et la Libert\u00e9',desc:'L\'Islam est accus\u00e9 de supprimer les libert\u00e9s. La v\u00e9rit\u00e9 est que l\'Islam a garanti la libert\u00e9 de croyance et interdit la coercition religieuse.',verse:'La v\u00e9rit\u00e9 vient de votre Seigneur. Quiconque veut, qu\'il croie',verseRef:'Sourate Al-Kahf 18:29',action:'Lisez la Charte de M\u00e9dine qui garantissait la libert\u00e9 aux non-musulmans'}},
{id:5,emoji:'🤝',ar:{title:'الإسلام والتسامح',desc:'يُوصف الإسلام بالتعصب. والحقيقة أن تاريخ الإسلام مليء بنماذج التسامح مع أهل الكتاب والأقليات.',verse:'لَا يَنْهَاكُمُ اللَّهُ عَنِ الَّذِينَ لَمْ يُقَاتِلُوكُمْ فِي الدِّينِ أَن تَبَرُّوهُمْ',verseRef:'سورة الممتحنة ٦٠: ٨',action:'تعرّف على معاملة المسلمين لغير المسلمين عبر التاريخ'},en:{title:'Islam and Tolerance',desc:'Islam is described as intolerant. The truth is Islamic history is full of examples of tolerance toward People of the Book and minorities.',verse:'God does not forbid you from being kind to those who do not fight you',verseRef:'Surah Al-Mumtahanah 60:8',action:'Learn how Muslims treated non-Muslims throughout history'},fr:{title:'L\'Islam et la Tol\u00e9rance',desc:'L\'Islam est d\u00e9crit comme intol\u00e9rant. La v\u00e9rit\u00e9 est que l\'histoire islamique regorge d\'exemples de tol\u00e9rance.',verse:'Dieu ne vous interdit pas d\'\u00eatre bons envers ceux qui ne vous combattent pas',verseRef:'Sourate Al-Mumtahanah 60:8',action:'D\u00e9couvrez comment les musulmans traitaient les non-musulmans'}},
{id:6,emoji:'🌍',ar:{title:'الإسلام والحداثة',desc:'يُقال إن الإسلام غير صالح لهذا العصر. والحقيقة أن مبادئ الإسلام صالحة لكل زمان ومكان لأنها مبادئ عامة مرنة.',verse:'مَا فَرَّطْنَا فِي الْكِتَابِ مِن شَيْءٍ',verseRef:'سورة الأنعام ٦: ٣٨',action:'فكر في مبدأ إسلامي واحد وكيف يناسب الحياة المعاصرة'},en:{title:'Islam and Modernity',desc:'It is said Islam is unsuitable for this era. The truth is Islamic principles are valid for all times and places because they are general and flexible.',verse:'We have not neglected anything in the Book',verseRef:'Surah Al-An\'am 6:38',action:'Think of one Islamic principle and how it fits modern life'},fr:{title:'L\'Islam et la Modernit\u00e9',desc:'On dit que l\'Islam n\'est pas adapt\u00e9 \u00e0 cette \u00e8re. La v\u00e9rit\u00e9 est que les principes islamiques sont valides pour tous les temps.',verse:'Nous n\'avons rien omis dans le Livre',verseRef:'Sourate Al-An\'am 6:38',action:'Pensez \u00e0 un principe islamique et comment il s\'adapte \u00e0 la vie moderne'}},
{id:7,emoji:'📖',ar:{title:'تحريف الحقائق',desc:'كثير من الاتهامات تعتمد على أحاديث ضعيفة أو آيات مقتطعة من سياقها. فهم القرآن يتطلب معرفة سبب النزول والسياق الكامل.',verse:'أَفَلَا يَتَدَبَّرُونَ الْقُرْآنَ',verseRef:'سورة محمد ٤٧: ٢٤',action:'عندما تسمع اتهاماً، ابحث عن سياق الآية أو الحديث المستشهد به'},en:{title:'Distortion of Facts',desc:'Many accusations rely on weak hadiths or verses taken out of context. Understanding the Quran requires knowing the reasons for revelation and full context.',verse:'Do they not reflect upon the Quran?',verseRef:'Surah Muhammad 47:24',action:'When you hear an accusation, research the context of the cited verse or hadith'},fr:{title:'D\u00e9formation des Faits',desc:'Beaucoup d\'accusations reposent sur des hadiths faibles ou des versets hors contexte. Comprendre le Coran n\u00e9cessite le contexte complet.',verse:'Ne m\u00e9ditent-ils pas sur le Coran ?',verseRef:'Sourate Muhammad 47:24',action:'Quand vous entendez une accusation, recherchez le contexte du verset cit\u00e9'}},
{id:8,emoji:'⚖️',ar:{title:'العدالة في الإسلام',desc:'يُتّهم الإسلام بالظلم في أحكامه. والحقيقة أن العدالة ركن أساسي — حتى مع الأعداء.',verse:'وَلَا يَجْرِمَنَّكُمْ شَنَآنُ قَوْمٍ عَلَىٰ أَلَّا تَعْدِلُوا',verseRef:'سورة المائدة ٥: ٨',action:'تأمل كيف يأمر الإسلام بالعدل حتى مع من نكره'},en:{title:'Justice in Islam',desc:'Islam is accused of injustice in its rulings. The truth is justice is a fundamental pillar — even with enemies.',verse:'Do not let hatred of a people prevent you from being just',verseRef:'Surah Al-Ma\'idah 5:8',action:'Reflect on how Islam commands justice even toward those we dislike'},fr:{title:'La Justice en Islam',desc:'L\'Islam est accus\u00e9 d\'injustice dans ses r\u00e8gles. La v\u00e9rit\u00e9 est que la justice est un pilier fondamental.',verse:'Que la haine d\'un peuple ne vous incite pas \u00e0 \u00eatre injustes',verseRef:'Sourate Al-Ma\'idah 5:8',action:'R\u00e9fl\u00e9chissez \u00e0 comment l\'Islam ordonne la justice m\u00eame envers ceux que nous n\'aimons pas'}},
{id:9,emoji:'🕊️',ar:{title:'الجهاد المفترى عليه',desc:'الجهاد ليس حرباً مقدسة عشوائية. جهاد النفس هو الجهاد الأكبر. القتال لا يكون إلا دفاعاً عن النفس والعرض والدين.',verse:'أُذِنَ لِلَّذِينَ يُقَاتَلُونَ بِأَنَّهُمْ ظُلِمُوا',verseRef:'سورة الحج ٢٢: ٣٩',action:'تعلّم الفرق بين أنواع الجهاد في الإسلام'},en:{title:'Jihad Falsely Accused',desc:'Jihad is not random holy war. Jihad of the self is the greatest jihad. Fighting is only in self-defense.',verse:'Permission is given to those who are fought because they were wronged',verseRef:'Surah Al-Hajj 22:39',action:'Learn the difference between types of jihad in Islam'},fr:{title:'Le Jihad Faussement Accus\u00e9',desc:'Le jihad n\'est pas une guerre sainte al\u00e9atoire. Le jihad de l\'\u00e2me est le plus grand jihad. Le combat n\'est qu\'en l\u00e9gitime d\u00e9fense.',verse:'Autorisation est donn\u00e9e \u00e0 ceux qui sont combattus parce qu\'ils ont \u00e9t\u00e9 l\u00e9s\u00e9s',verseRef:'Sourate Al-Hajj 22:39',action:'Apprenez la diff\u00e9rence entre les types de jihad en Islam'}},
{id:10,emoji:'🏛️',ar:{title:'الإسلام والديمقراطية',desc:'يُقال إن الإسلام ضد الديمقراطية. والحقيقة أن مبدأ الشورى في الإسلام سبق الديمقراطية الحديثة بقرون.',verse:'وَأَمْرُهُمْ شُورَىٰ بَيْنَهُمْ',verseRef:'سورة الشورى ٤٢: ٣٨',action:'قارن بين مبدأ الشورى والديمقراطية الحديثة'},en:{title:'Islam and Democracy',desc:'It is said Islam opposes democracy. The truth is the principle of shura preceded modern democracy by centuries.',verse:'And their affairs are by consultation among them',verseRef:'Surah Ash-Shura 42:38',action:'Compare the principle of shura with modern democracy'},fr:{title:'L\'Islam et la D\u00e9mocratie',desc:'On dit que l\'Islam s\'oppose \u00e0 la d\u00e9mocratie. La v\u00e9rit\u00e9 est que le principe de shura a pr\u00e9c\u00e9d\u00e9 la d\u00e9mocratie moderne de si\u00e8cles.',verse:'Et leur affaire est par consultation entre eux',verseRef:'Sourate Ash-Shura 42:38',action:'Comparez le principe de shura avec la d\u00e9mocratie moderne'}},
{id:11,emoji:'🌿',ar:{title:'الإسلام والبيئة',desc:'الإسلام سبق العالم في حماية البيئة. نهى النبي ﷺ عن قطع الأشجار حتى في الحرب وجعل إماطة الأذى عن الطريق صدقة.',verse:'وَلَا تُفْسِدُوا فِي الْأَرْضِ بَعْدَ إِصْلَاحِهَا',verseRef:'سورة الأعراف ٧: ٥٦',action:'قم بعمل بيئي اليوم مستلهماً من تعاليم الإسلام'},en:{title:'Islam and the Environment',desc:'Islam preceded the world in environmental protection. The Prophet ﷺ forbade cutting trees even in war and made removing harm from roads a charity.',verse:'And do not cause corruption on earth after its reformation',verseRef:'Surah Al-A\'raf 7:56',action:'Do an environmental act today inspired by Islamic teachings'},fr:{title:'L\'Islam et l\'Environnement',desc:'L\'Islam a pr\u00e9c\u00e9d\u00e9 le monde dans la protection de l\'environnement. Le Proph\u00e8te ﷺ a interdit de couper les arbres m\u00eame en guerre.',verse:'Et ne semez pas la corruption sur terre apr\u00e8s sa r\u00e9forme',verseRef:'Sourate Al-A\'raf 7:56',action:'Faites un geste environnemental aujourd\'hui inspir\u00e9 par l\'Islam'}},
{id:12,emoji:'📜',ar:{title:'حقوق الإنسان',desc:'الإسلام كفل حقوق الإنسان قبل الإعلان العالمي بـ ١٤ قرناً: حق الحياة والكرامة والملكية والتعليم.',verse:'وَلَقَدْ كَرَّمْنَا بَنِي آدَمَ',verseRef:'سورة الإسراء ١٧: ٧٠',action:'قارن بين خطبة حجة الوداع وإعلان حقوق الإنسان'},en:{title:'Human Rights',desc:'Islam guaranteed human rights 14 centuries before the Universal Declaration: rights to life, dignity, property, and education.',verse:'We have honored the children of Adam',verseRef:'Surah Al-Isra 17:70',action:'Compare the Farewell Sermon with the Universal Declaration of Human Rights'},fr:{title:'Droits de l\'Homme',desc:'L\'Islam a garanti les droits de l\'homme 14 si\u00e8cles avant la D\u00e9claration universelle : droits \u00e0 la vie, la dignit\u00e9, la propri\u00e9t\u00e9 et l\'\u00e9ducation.',verse:'Nous avons honor\u00e9 les fils d\'Adam',verseRef:'Sourate Al-Isra 17:70',action:'Comparez le Sermon d\'Adieu avec la D\u00e9claration universelle'}},
{id:13,emoji:'🕌',ar:{title:'الإسلام والفنون',desc:'يُزعم أن الإسلام عدو الفن. والحقيقة أن الحضارة الإسلامية أنتجت أروع الفنون المعمارية والخط العربي والزخرفة.',verse:'إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ',verseRef:'حديث صحيح',action:'زر مسجداً قريباً وتأمل جمال عمارته'},en:{title:'Islam and the Arts',desc:'It is claimed Islam is an enemy of art. The truth is Islamic civilization produced the finest architecture, calligraphy, and decorative arts.',verse:'Indeed, God is beautiful and loves beauty',verseRef:'Authentic hadith',action:'Visit a nearby mosque and appreciate its architectural beauty'},fr:{title:'L\'Islam et les Arts',desc:'On pr\u00e9tend que l\'Islam est ennemi de l\'art. La v\u00e9rit\u00e9 est que la civilisation islamique a produit les plus beaux arts.',verse:'Certes, Dieu est beau et aime la beaut\u00e9',verseRef:'Hadith authentique',action:'Visitez une mosqu\u00e9e et appr\u00e9ciez la beaut\u00e9 de son architecture'}},
{id:14,emoji:'🧠',ar:{title:'الإسلام والعقل',desc:'الإسلام لا يقمع العقل بل يدعو للتفكير والتأمل. القرآن مليء بآيات تحث على التفكر والتعقل.',verse:'أَفَلَا تَعْقِلُونَ',verseRef:'سورة البقرة ٢: ٤٤',action:'تأمل في آية قرآنية اليوم واستخدم عقلك لفهمها'},en:{title:'Islam and Reason',desc:'Islam does not suppress reason but calls for thinking and reflection. The Quran is full of verses urging contemplation.',verse:'Will you not use reason?',verseRef:'Surah Al-Baqarah 2:44',action:'Contemplate a Quranic verse today and use your mind to understand it'},fr:{title:'L\'Islam et la Raison',desc:'L\'Islam ne supprime pas la raison mais appelle \u00e0 la r\u00e9flexion. Le Coran est plein de versets invitant \u00e0 la contemplation.',verse:'Ne raisonnez-vous pas ?',verseRef:'Sourate Al-Baqarah 2:44',action:'M\u00e9ditez un verset coranique aujourd\'hui et utilisez votre raison'}},
{id:15,emoji:'🌐',ar:{title:'الإسلام والعولمة',desc:'الإسلام دين عالمي منذ البداية. لا فضل لعربي على أعجمي إلا بالتقوى.',verse:'يَا أَيُّهَا النَّاسُ إِنَّا خَلَقْنَاكُم مِّن ذَكَرٍ وَأُنثَىٰ',verseRef:'سورة الحجرات ٤٩: ١٣',action:'تعرّف على مسلم من ثقافة مختلفة'},en:{title:'Islam and Globalization',desc:'Islam has been a universal religion from the beginning. No Arab is superior to a non-Arab except through piety.',verse:'O mankind, We have created you from male and female',verseRef:'Surah Al-Hujurat 49:13',action:'Get to know a Muslim from a different culture'},fr:{title:'L\'Islam et la Mondialisation',desc:'L\'Islam est une religion universelle depuis le d\u00e9but. Aucun Arabe n\'est sup\u00e9rieur sauf par la pi\u00e9t\u00e9.',verse:'\u00d4 humanit\u00e9, Nous vous avons cr\u00e9\u00e9s d\'un m\u00e2le et d\'une femelle',verseRef:'Sourate Al-Hujurat 49:13',action:'Faites connaissance avec un musulman d\'une culture diff\u00e9rente'}},
{id:16,emoji:'❤️',ar:{title:'الإسلام والرحمة',desc:'الإسلام بُني على الرحمة لا القسوة. الرحمة أساس كل تشريع إسلامي.',verse:'كَتَبَ رَبُّكُمْ عَلَىٰ نَفْسِهِ الرَّحْمَةَ',verseRef:'سورة الأنعام ٦: ٥٤',action:'عامل كل من حولك اليوم بالرحمة'},en:{title:'Islam and Mercy',desc:'Islam is built on mercy, not cruelty. Mercy is the foundation of every Islamic legislation.',verse:'Your Lord has decreed upon Himself mercy',verseRef:'Surah Al-An\'am 6:54',action:'Treat everyone around you with mercy today'},fr:{title:'L\'Islam et la Mis\u00e9ricorde',desc:'L\'Islam est fond\u00e9 sur la mis\u00e9ricorde, pas la cruaut\u00e9. La mis\u00e9ricorde est le fondement de chaque l\u00e9gislation islamique.',verse:'Votre Seigneur S\'est prescrit la mis\u00e9ricorde',verseRef:'Sourate Al-An\'am 6:54',action:'Traitez tout le monde avec mis\u00e9ricorde aujourd\'hui'}},
{id:17,emoji:'📚',ar:{title:'أخلاق الحوار',desc:'الإسلام يعلّمنا أدب الحوار والنقاش. الرد على الشبهات يكون بالحكمة والحجة لا بالعنف والتعصب.',verse:'ادْعُ إِلَىٰ سَبِيلِ رَبِّكَ بِالْحِكْمَةِ وَالْمَوْعِظَةِ الْحَسَنَةِ',verseRef:'سورة النحل ١٦: ١٢٥',action:'عندما تسمع انتقاداً للإسلام، رد بأدب وحجة'},en:{title:'Ethics of Dialogue',desc:'Islam teaches us the etiquette of dialogue and discussion. Responding to doubts should be with wisdom, not violence.',verse:'Invite to the way of your Lord with wisdom and good instruction',verseRef:'Surah An-Nahl 16:125',action:'When you hear criticism of Islam, respond with courtesy and evidence'},fr:{title:'\u00c9thique du Dialogue',desc:'L\'Islam nous enseigne l\'\u00e9tiquette du dialogue. R\u00e9pondre aux doutes doit se faire avec sagesse, pas violence.',verse:'Appelle au chemin de ton Seigneur avec sagesse et bonne exhortation',verseRef:'Sourate An-Nahl 16:125',action:'Quand vous entendez une critique de l\'Islam, r\u00e9pondez avec courtoisie'}},
{id:18,emoji:'🏥',ar:{title:'الطب والصحة',desc:'الإسلام سبق العالم في مفاهيم الصحة والنظافة: الوضوء والغسل وآداب الطعام والحجر الصحي.',verse:'إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ',verseRef:'سورة البقرة ٢: ٢٢٢',action:'تأمل كيف يحافظ الوضوء على نظافة جسمك ٥ مرات يومياً'},en:{title:'Medicine and Health',desc:'Islam preceded the world in health concepts: ablution, bathing, food etiquette, and quarantine.',verse:'Indeed, Allah loves those who repent and loves those who purify themselves',verseRef:'Surah Al-Baqarah 2:222',action:'Reflect on how wudu keeps your body clean 5 times daily'},fr:{title:'M\u00e9decine et Sant\u00e9',desc:'L\'Islam a pr\u00e9c\u00e9d\u00e9 le monde dans les concepts de sant\u00e9 : ablution, bain, \u00e9tiquette alimentaire et quarantaine.',verse:'Certes, Allah aime ceux qui se repentent et ceux qui se purifient',verseRef:'Sourate Al-Baqarah 2:222',action:'R\u00e9fl\u00e9chissez \u00e0 comment le wudu garde votre corps propre 5 fois par jour'}},
{id:19,emoji:'🎓',ar:{title:'التعليم والمعرفة',desc:'أول كلمة في القرآن هي "اقرأ". الإسلام جعل طلب العلم فريضة على كل مسلم ومسلمة.',verse:'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',verseRef:'سورة العلق ٩٦: ١',action:'تعلّم شيئاً جديداً اليوم — العلم في الإسلام عبادة'},en:{title:'Education and Knowledge',desc:'The first word revealed in the Quran was "Read." Islam made seeking knowledge an obligation for every Muslim.',verse:'Read in the name of your Lord who created',verseRef:'Surah Al-Alaq 96:1',action:'Learn something new today — knowledge in Islam is worship'},fr:{title:'\u00c9ducation et Connaissance',desc:'Le premier mot r\u00e9v\u00e9l\u00e9 du Coran \u00e9tait "Lis". L\'Islam a fait de la qu\u00eate du savoir une obligation pour chaque musulman.',verse:'Lis au nom de ton Seigneur qui a cr\u00e9\u00e9',verseRef:'Sourate Al-Alaq 96:1',action:'Apprenez quelque chose de nouveau aujourd\'hui — le savoir est adoration'}},
{id:20,emoji:'🌏',ar:{title:'رسالتنا اليوم',desc:'مهمتنا ليست فقط الدفاع بل تقديم صورة صحيحة عن الإسلام بأخلاقنا قبل أقوالنا. نحن سفراء الإسلام.',verse:'كُنتُمْ خَيْرَ أُمَّةٍ أُخْرِجَتْ لِلنَّاسِ',verseRef:'سورة آل عمران ٣: ١١٠',action:'كن سفيراً للإسلام اليوم بأخلاقك الحسنة'},en:{title:'Our Mission Today',desc:'Our mission is not just defense but presenting a correct image of Islam through our character before our words. We are Islam\'s ambassadors.',verse:'You are the best nation produced for mankind',verseRef:'Surah Aal-Imran 3:110',action:'Be an ambassador for Islam today through your good character'},fr:{title:'Notre Mission Aujourd\'hui',desc:'Notre mission n\'est pas seulement la d\u00e9fense mais pr\u00e9senter une image correcte de l\'Islam par notre caract\u00e8re. Nous sommes les ambassadeurs de l\'Islam.',verse:'Vous \u00eates la meilleure communaut\u00e9 produite pour l\'humanit\u00e9',verseRef:'Sourate Aal-Imran 3:110',action:'Soyez un ambassadeur de l\'Islam aujourd\'hui par votre bon caract\u00e8re'}}
];

const DEFENSE_DATA=[
{emoji:'⚔️',ar:{title:'الرد على تهمة العنف',text:'الإسلام دين السلام وليس العنف',problem:'يُستشهد بآيات القتال دون سياقها التاريخي',solution:'هذه الآيات نزلت في ظروف حرب دفاعية محددة ولا تُعمّم'},en:{title:'Responding to Violence Accusation',text:'Islam is a religion of peace, not violence',problem:'Fighting verses are cited without historical context',solution:'These verses were revealed in specific defensive war circumstances and cannot be generalized'},fr:{title:'R\u00e9pondre \u00e0 l\'Accusation de Violence',text:'L\'Islam est une religion de paix',problem:'Les versets de combat sont cit\u00e9s sans contexte historique',solution:'Ces versets ont \u00e9t\u00e9 r\u00e9v\u00e9l\u00e9s dans des circonstances d\u00e9fensives sp\u00e9cifiques'}},
{emoji:'👩',ar:{title:'الرد على تهمة اضطهاد المرأة',text:'الإسلام كرّم المرأة في كل المجالات',problem:'يُستشهد بممارسات ثقافية وليست دينية',solution:'فرّق بين الدين والثقافة — الإسلام أعطى المرأة حقوقها كاملة'},en:{title:'Responding to Women\'s Oppression',text:'Islam honored women in all fields',problem:'Cultural practices are cited as religious ones',solution:'Distinguish between religion and culture — Islam gave women full rights'},fr:{title:'R\u00e9pondre \u00e0 l\'Oppression des Femmes',text:'L\'Islam a honor\u00e9 les femmes dans tous les domaines',problem:'Des pratiques culturelles sont cit\u00e9es comme religieuses',solution:'Distinguez entre religion et culture — l\'Islam a donn\u00e9 aux femmes tous leurs droits'}},
{emoji:'🔬',ar:{title:'الرد على تهمة العداء للعلم',text:'العلم فريضة في الإسلام',problem:'يُنسب تخلف بعض المسلمين إلى الإسلام',solution:'التخلف سببه الجهل بالدين لا الدين نفسه — الحضارة الإسلامية دليل'},en:{title:'Responding to Anti-Science Accusation',text:'Knowledge is an obligation in Islam',problem:'Backwardness of some Muslims is attributed to Islam',solution:'Backwardness is caused by ignorance of religion, not religion itself'},fr:{title:'R\u00e9pondre \u00e0 l\'Anti-Science',text:'Le savoir est une obligation en Islam',problem:'Le retard de certains musulmans est attribu\u00e9 \u00e0 l\'Islam',solution:'Le retard est caus\u00e9 par l\'ignorance de la religion, pas la religion elle-m\u00eame'}},
{emoji:'🗣️',ar:{title:'الرد على تهمة قمع الحريات',text:'الإسلام كفل الحرية الدينية والفكرية',problem:'يُستشهد بقوانين بشرية لا بتعاليم إسلامية',solution:'الإسلام يقول: لا إكراه في الدين — هذا نص قاطع لا يقبل التأويل'},en:{title:'Responding to Freedom Suppression',text:'Islam guaranteed religious and intellectual freedom',problem:'Human laws are cited instead of Islamic teachings',solution:'Islam says: No compulsion in religion — this is a definitive, unambiguous text'},fr:{title:'R\u00e9pondre \u00e0 la Suppression des Libert\u00e9s',text:'L\'Islam a garanti la libert\u00e9 religieuse et intellectuelle',problem:'Des lois humaines sont cit\u00e9es au lieu des enseignements islamiques',solution:'L\'Islam dit : Nulle contrainte en religion — un texte d\u00e9finitif et sans ambigu\u00eft\u00e9'}},
{emoji:'🌍',ar:{title:'الرد على تهمة التعصب',text:'الإسلام دين التسامح والتعايش',problem:'أفعال بعض المتطرفين تُنسب للإسلام',solution:'لا يُحكم على دين بأخطاء أتباعه — الإسلام يُحكم عليه بنصوصه'},en:{title:'Responding to Intolerance Accusation',text:'Islam is a religion of tolerance and coexistence',problem:'Actions of some extremists are attributed to Islam',solution:'A religion cannot be judged by its followers\' mistakes — judge Islam by its texts'},fr:{title:'R\u00e9pondre \u00e0 l\'Intol\u00e9rance',text:'L\'Islam est une religion de tol\u00e9rance et coexistence',problem:'Les actions de certains extr\u00e9mistes sont attribu\u00e9es \u00e0 l\'Islam',solution:'On ne juge pas une religion par les erreurs de ses adeptes — jugez l\'Islam par ses textes'}}
];

const HABITS=[
{emoji:'📖',ar:{label:'قراءة عن الإسلام يومياً',source:'المعرفة'},en:{label:'Read about Islam daily',source:'Knowledge'},fr:{label:'Lire sur l\'Islam quotidiennement',source:'Connaissance'}},
{emoji:'🤝',ar:{label:'تعامل بأخلاق حسنة',source:'السفير'},en:{label:'Act with good character',source:'Ambassador'},fr:{label:'Agissez avec bon caract\u00e8re',source:'Ambassadeur'}},
{emoji:'💡',ar:{label:'تعلّم حجة واحدة جديدة',source:'الدفاع'},en:{label:'Learn one new argument',source:'Defense'},fr:{label:'Apprenez un nouvel argument',source:'D\u00e9fense'}},
{emoji:'🗣️',ar:{label:'ناقش بأدب واحترام',source:'الحوار'},en:{label:'Discuss with courtesy',source:'Dialogue'},fr:{label:'Discutez avec courtoisie',source:'Dialogue'}},
{emoji:'📿',ar:{label:'ادعُ للمسلمين والإنسانية',source:'الدعاء'},en:{label:'Pray for Muslims and humanity',source:'Dua'},fr:{label:'Priez pour les musulmans et l\'humanit\u00e9',source:'Dua'}},
{emoji:'😊',ar:{label:'ابتسم وانشر الإيجابية',source:'الأخلاق'},en:{label:'Smile and spread positivity',source:'Character'},fr:{label:'Souriez et r\u00e9pandez la positivit\u00e9',source:'Caract\u00e8re'}},
{emoji:'🌿',ar:{label:'قم بعمل خيري',source:'السفارة'},en:{label:'Do a charitable act',source:'Ambassadorship'},fr:{label:'Faites un acte de charit\u00e9',source:'Ambassade'}},
{emoji:'🔍',ar:{label:'تحقق من معلومة قبل نشرها',source:'المسؤولية'},en:{label:'Verify info before sharing',source:'Responsibility'},fr:{label:'V\u00e9rifiez avant de partager',source:'Responsabilit\u00e9'}}
];

const QUIZ=[
{ar:'هل تستطيع الرد على تهمة العنف في الإسلام؟',en:'Can you respond to the violence accusation against Islam?',fr:'Pouvez-vous r\u00e9pondre \u00e0 l\'accusation de violence ?'},
{ar:'هل تخلط بين الثقافة والدين أحياناً؟',en:'Do you sometimes confuse culture and religion?',fr:'Confondez-vous parfois culture et religion ?'},
{ar:'هل تعرف حقوق المرأة في الإسلام؟',en:'Do you know women\'s rights in Islam?',fr:'Connaissez-vous les droits des femmes en Islam ?'},
{ar:'هل تقرأ الآيات في سياقها قبل الحكم؟',en:'Do you read verses in context before judging?',fr:'Lisez-vous les versets en contexte avant de juger ?'},
{ar:'هل تنزعج بسهولة من انتقاد الإسلام؟',en:'Do you easily get upset by criticism of Islam?',fr:'Vous \u00e9nervez-vous facilement face aux critiques de l\'Islam ?'},
{ar:'هل تعرف إنجازات الحضارة الإسلامية في العلم؟',en:'Do you know Islamic civilization\'s scientific achievements?',fr:'Connaissez-vous les r\u00e9alisations scientifiques de la civilisation islamique ?'},
{ar:'هل تدافع عن الإسلام بالحكمة أم بالعاطفة؟',en:'Do you defend Islam with wisdom or emotion?',fr:'D\u00e9fendez-vous l\'Islam avec sagesse ou \u00e9motion ?'},
{ar:'هل تعرف الفرق بين أنواع الجهاد؟',en:'Do you know the difference between types of jihad?',fr:'Connaissez-vous la diff\u00e9rence entre les types de jihad ?'},
{ar:'هل تقدم صورة حسنة عن الإسلام بأخلاقك؟',en:'Do you present a good image of Islam through your character?',fr:'Pr\u00e9sentez-vous une bonne image de l\'Islam par votre caract\u00e8re ?'},
{ar:'هل تعرف مبدأ الشورى وكيف يشبه الديمقراطية؟',en:'Do you know the principle of shura and how it resembles democracy?',fr:'Connaissez-vous le principe de shura et comment il ressemble \u00e0 la d\u00e9mocratie ?'}
];

const DUAS=[
{ar:{label:'دعاء الحق',text:'اللَّهُمَّ أَرِنَا الْحَقَّ حَقًّا وَارْزُقْنَا اتِّبَاعَهُ',tr:'اللهم أرنا الحق حقاً وارزقنا اتباعه وأرنا الباطل باطلاً وارزقنا اجتنابه'},en:{label:'Dua for Truth',text:'O Allah, show us the truth as truth and grant us to follow it',tr:'And show us falsehood as falsehood and grant us to avoid it'},fr:{label:'Dua pour la V\u00e9rit\u00e9',text:'\u00d4 Allah, montre-nous la v\u00e9rit\u00e9 comme v\u00e9rit\u00e9 et accorde-nous de la suivre',tr:'Et montre-nous le faux comme faux et accorde-nous de l\'\u00e9viter'}},
{ar:{label:'دعاء الثبات',text:'يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ',tr:'يا مقلب القلوب ثبت قلبي على دينك'},en:{label:'Dua for Steadfastness',text:'O Turner of hearts, make my heart firm upon Your religion',tr:'O Turner of hearts, keep my heart firm on Your religion'},fr:{label:'Dua pour la Constance',text:'\u00d4 Celui qui retourne les c\u0153urs, affermis mon c\u0153ur sur Ta religion',tr:'Affermis mon c\u0153ur sur Ta religion'}},
{ar:{label:'دعاء النصرة',text:'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا',tr:'ربنا أفرغ علينا صبراً وثبت أقدامنا وانصرنا على القوم الكافرين'},en:{label:'Dua for Victory',text:'Our Lord, pour upon us patience, plant our feet firmly',tr:'Our Lord, pour upon us patience, plant our feet firmly and aid us against the disbelieving people'},fr:{label:'Dua pour la Victoire',text:'Notre Seigneur, d\u00e9verse sur nous la patience et affermis nos pas',tr:'Notre Seigneur, d\u00e9verse sur nous la patience, affermis nos pas et aide-nous'}},
{ar:{label:'دعاء الحكمة',text:'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي',tr:'ربي اشرح لي صدري ويسر لي أمري واحلل عقدة من لساني'},en:{label:'Dua for Wisdom',text:'My Lord, expand for me my chest and ease for me my task',tr:'And untie the knot from my tongue so they may understand my speech'},fr:{label:'Dua pour la Sagesse',text:'Mon Seigneur, \u00e9largis ma poitrine et facilite ma t\u00e2che',tr:'Et d\u00e9noue le n\u0153ud de ma langue pour qu\'ils comprennent ma parole'}},
{ar:{label:'دعاء الهداية',text:'اللَّهُمَّ اهْدِنَا فِيمَنْ هَدَيْتَ',tr:'اللهم اهدنا فيمن هديت وعافنا فيمن عافيت'},en:{label:'Dua for Guidance',text:'O Allah, guide us among those You have guided',tr:'And grant us well-being among those You have granted'},fr:{label:'Dua pour la Guidance',text:'\u00d4 Allah, guide-nous parmi ceux que Tu as guid\u00e9s',tr:'Et accorde-nous le bien-\u00eatre parmi ceux \u00e0 qui Tu l\'as accord\u00e9'}},
{ar:{label:'دعاء العلم',text:'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا',tr:'اللهم إني أسألك علماً نافعاً ورزقاً طيباً وعملاً متقبلاً'},en:{label:'Dua for Knowledge',text:'O Allah, I ask You for beneficial knowledge',tr:'O Allah, grant me beneficial knowledge, good provision, and accepted deeds'},fr:{label:'Dua pour le Savoir',text:'\u00d4 Allah, je Te demande un savoir b\u00e9n\u00e9fique',tr:'\u00d4 Allah, accorde-moi un savoir utile, une bonne subsistance et des actes accept\u00e9s'}}
];

let lang=localStorage.getItem('im-lang')||'ar';let theme=localStorage.getItem('im-theme')||'amber';const themes=['amber','night','garden'];const themeIcons=['🔥','🌙','🌿'];const themeNames={amber:'🔥',night:'🌙 Night',garden:'🌿 Garden'};let currentCardIdx=-1;

document.addEventListener('DOMContentLoaded',()=>{setTheme(theme);setLang(lang);initTabs();initSplash();initScrollTop();renderHome();renderCards();renderDefense();renderHabits();renderQuiz();renderAbout();renderHelp();renderDuas();initScrollReveal();initKeyboardNav();});

function initSplash(){let c=5;const el=document.getElementById('splashCount');const fe=document.getElementById('splashFeatures');if(fe)fe.innerHTML=T[lang].splashFeatures.map((f,i)=>`<div class="splash-feature" style="animation-delay:${0.3+i*0.3}s">${f}</div>`).join('');const iv=setInterval(()=>{c--;if(el)el.textContent=c;if(c<=0){dismissSplash();clearInterval(iv);}},1000);}
function dismissSplash(){const s=document.getElementById('splash');if(s){s.classList.add('hidden');setTimeout(()=>s.style.display='none',500);}playSound('click');}

function setLang(l){lang=l;localStorage.setItem('im-lang',l);const isRTL=l==='ar';document.documentElement.lang=l;document.documentElement.dir=isRTL?'rtl':'ltr';document.body.dir=isRTL?'rtl':'ltr';document.querySelectorAll('.lang-opt').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));const t=T[l];const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};set('appTitle',t.appTitle);set('splashSub',t.splashSub);set('splashHint',t.splashHint);set('tabHome',t.tabHome);set('tabCards',t.tabCards);set('tabDefense',t.tabDefense);set('tabHabits',t.tabHabits);set('tabQuiz',t.tabQuiz);set('tabAbout',t.tabAbout);set('cardsTitle',t.cardsTitle);set('cardsDesc',t.cardsDesc);set('defenseTitle',t.defenseTitle);set('defenseDesc',t.defenseDesc);set('habitsTitle',t.habitsTitle);set('habitsDesc',t.habitsDesc);set('quizTitle',t.quizTitle);set('quizDesc',t.quizDesc);set('helpTitle',t.helpTitle);set('duaPanelTitle',t.duaPanelTitle);set('habitsReset',t.resetBtn);renderHome();renderCards();renderDefense();renderHabits();renderQuiz();renderAbout();renderHelp();renderDuas();const fe=document.getElementById('splashFeatures');if(fe)fe.innerHTML=T[l].splashFeatures.map((f,i)=>`<div class="splash-feature" style="animation-delay:${0.3+i*0.3}s">${f}</div>`).join('');}

function setTheme(t){theme=t;document.documentElement.dataset.theme=t;localStorage.setItem('im-theme',t);const idx=themes.indexOf(t);const el=document.getElementById('themeIcon');if(el)el.textContent=themeIcons[idx];}
function cycleTheme(){const idx=(themes.indexOf(theme)+1)%themes.length;setTheme(themes[idx]);showToast(themeNames[themes[idx]]);playSound('theme');}

function initTabs(){document.querySelectorAll('.tab').forEach(tab=>{tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');const panel=document.getElementById('panel-'+tab.dataset.tab);if(panel)panel.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});playSound('click');});});}

function renderHome(){const t=T[lang];const dayIdx=new Date().getDate()%CARDS.length;const c=CARDS[dayIdx];const cd=c[lang];document.getElementById('dailyCard').innerHTML=`<div class="daily-label">${t.dailyLabel}</div><div class="daily-title">${cd.title}</div><div class="daily-body">${cd.desc}</div><div class="daily-action" onclick="document.querySelector('[data-tab=cards]').click()">${t.tabCards} &#8594;</div>`;const sections=[{icon:'⚖️',tab:'cards',title:t.tabCards,desc:lang==='ar'?'٢٠ رد على الافتراءات':lang==='fr'?'20 r\u00e9futations':'20 refutations'},{icon:'🛡️',tab:'defense',title:t.tabDefense,desc:lang==='ar'?'خط الدفاع':lang==='fr'?'Ligne de d\u00e9fense':'Line of defense'},{icon:'📋',tab:'habits',title:t.tabHabits,desc:lang==='ar'?'عادات المدافع':lang==='fr'?'Habitudes':'Habits'},{icon:'🤔',tab:'quiz',title:t.tabQuiz,desc:lang==='ar'?'اختبر نفسك':lang==='fr'?'Testez-vous':'Test yourself'},{icon:'📖',tab:'about',title:t.tabAbout,desc:lang==='ar'?'عن الكتاب':lang==='fr'?'Le livre':'About'}];document.getElementById('homeGrid').innerHTML=sections.map(s=>`<div class="home-card" onclick="document.querySelector('[data-tab=${s.tab}]').click()"><span class="hc-icon">${s.icon}</span><div class="hc-title">${s.title}</div><div class="hc-desc">${s.desc}</div></div>`).join('');}

function renderCards(){const t=T[lang];const sb=`<div class="search-bar"><input type="text" id="cardsSearch" class="search-input" placeholder="${t.searchPlaceholder}" oninput="filterCards(this.value)"><span class="search-icon">🔍</span></div>`;const cards=CARDS.map((c,i)=>{const d=c[lang];return`<div class="principle-card scroll-reveal" id="card-${c.id}" data-search="${d.title.toLowerCase()}"><div class="principle-head" onclick="toggleCard('card-${c.id}')"><span class="principle-num">${c.id}</span><span class="principle-emoji">${c.emoji}</span><span class="principle-title">${d.title}</span><span class="principle-chev">&#9660;</span></div><div class="principle-body"><div class="principle-inner"><p class="principle-desc">${d.desc}</p><div class="verse-box"><div class="verse-arabic">${d.verse}</div><div class="verse-ref">${d.verseRef}</div></div><div class="action-box"><span class="action-icon">💡</span><span>${d.action}</span></div><button class="share-btn" onclick="event.stopPropagation();shareCard(${i})"><span class="share-icon">&#128279;</span> ${t.share}</button></div></div></div>`;}).join('');document.getElementById('cardsContainer').innerHTML=sb+cards;}
function filterCards(q){q=q.toLowerCase().trim();document.querySelectorAll('.principle-card').forEach(c=>{const s=c.dataset.search||'';const t=c.querySelector('.principle-title');c.style.display=(!q||s.includes(q)||(t&&t.textContent.toLowerCase().includes(q)))?'':'none';});}
async function shareCard(idx){const c=CARDS[idx];const d=c[lang];const text=`${c.emoji} ${d.title}\n\n${d.desc}\n\n${d.verse}\n\n💡 ${d.action}\n\n— الإسلام المفترى عليه`;if(navigator.share){try{await navigator.share({title:d.title,text});}catch(e){}}else{try{await navigator.clipboard.writeText(text);showToast(lang==='ar'?'تم النسخ!':'Copied!');}catch(e){}}}

function renderDefense(){document.getElementById('defenseContainer').innerHTML=DEFENSE_DATA.map(a=>{const d=a[lang];return`<div class="anxiety-card scroll-reveal"><div class="anxiety-header"><span class="anxiety-emoji">${a.emoji}</span><span class="anxiety-title">${d.title}</span></div><div class="verse-box" style="margin-bottom:12px"><div class="verse-arabic">${d.text}</div></div><div class="anxiety-problem"><span class="anxiety-label">${lang==='ar'?'❌ الشبهة':lang==='fr'?'❌ L\'Accusation':'❌ The Accusation'}</span>${d.problem}</div><div class="anxiety-solution"><span class="anxiety-label">${lang==='ar'?'✅ الرد':lang==='fr'?'✅ La R\u00e9ponse':'✅ The Response'}</span>${d.solution}</div></div>`;}).join('');}

function renderHabits(){const today=new Date().toDateString();let hs=JSON.parse(localStorage.getItem('im-habits')||'{}');if(hs.date!==today){updateStreak(hs);hs={date:today,done:[]};localStorage.setItem('im-habits',JSON.stringify(hs));}const streak=getStreak();const sh=streak>0?`<div class="streak-badge">🔥 ${streak} ${T[lang].streakMsg}</div>`:'';document.getElementById('habitsContainer').innerHTML=HABITS.map((h,i)=>{const d=h[lang];const done=hs.done.includes(i);return`<div class="habit-item ${done?'done':''}" onclick="toggleHabit(${i})"><span class="habit-check">${done?'&#10003;':''}</span><span class="habit-emoji">${h.emoji}</span><div><div class="habit-label">${d.label}</div><div class="habit-source">${d.source}</div></div></div>`;}).join('');const se=document.getElementById('streakBadge');if(se)se.innerHTML=sh;updateHabitsProgress(hs);}
function toggleHabit(i){const today=new Date().toDateString();let hs=JSON.parse(localStorage.getItem('im-habits')||'{}');if(hs.date!==today)hs={date:today,done:[]};const idx=hs.done.indexOf(i);if(idx>-1)hs.done.splice(idx,1);else hs.done.push(i);localStorage.setItem('im-habits',JSON.stringify(hs));renderHabits();playSound(idx>-1?'click':'success');if(hs.done.length===HABITS.length){launchConfetti();showToast(T[lang].allDone);}}
function resetHabits(){localStorage.setItem('im-habits',JSON.stringify({date:new Date().toDateString(),done:[]}));renderHabits();showToast(lang==='ar'?'تم':'Reset');}
function updateHabitsProgress(hs){const d=hs.done.length,t=HABITS.length,p=t>0?(d/t*100):0;const f=document.getElementById('habitsFill');const tx=document.getElementById('habitsText');if(f)f.style.width=p+'%';if(tx)tx.textContent=`${d}/${t}`;}
function updateStreak(ps){let sd=JSON.parse(localStorage.getItem('im-streak')||'{"count":0,"lastDate":""}');if(ps&&ps.done&&ps.done.length===HABITS.length&&ps.date){const y=new Date();y.setDate(y.getDate()-1);if(ps.date===y.toDateString())sd.count++;else if(ps.date!==new Date().toDateString())sd.count=ps.done.length===HABITS.length?1:0;sd.lastDate=ps.date;}else if(ps&&ps.date){sd.count=0;sd.lastDate=ps.date;}localStorage.setItem('im-streak',JSON.stringify(sd));}
function getStreak(){return JSON.parse(localStorage.getItem('im-streak')||'{"count":0}').count;}

function launchConfetti(){const canvas=document.getElementById('confettiCanvas');if(!canvas)return;canvas.style.display='block';const ctx=canvas.getContext('2d');canvas.width=window.innerWidth;canvas.height=window.innerHeight;const ps=[];const colors=['#F57F17','#FFB300','#FFF176','#FFE082','#FF8F00','#F9A825'];for(let i=0;i<120;i++)ps.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height-canvas.height,w:Math.random()*10+5,h:Math.random()*6+3,color:colors[Math.floor(Math.random()*colors.length)],vx:(Math.random()-0.5)*4,vy:Math.random()*3+2,rot:Math.random()*360,rotSpeed:(Math.random()-0.5)*10});let frame=0;function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ps.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.rot+=p.rotSpeed;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot*Math.PI/180);ctx.fillStyle=p.color;ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);ctx.restore();});frame++;if(frame<120)requestAnimationFrame(draw);else{ctx.clearRect(0,0,canvas.width,canvas.height);canvas.style.display='none';}}draw();}

function renderQuiz(){const t=T[lang];document.getElementById('quizContainer').innerHTML=QUIZ.map((q,i)=>`<div class="quiz-question scroll-reveal" id="quiz-q-${i}"><div class="quiz-q-text">${i+1}. ${q[lang]}</div><div class="quiz-options"><button class="quiz-opt" onclick="selectQuizOpt(${i},2)">${lang==='ar'?'نعم':lang==='fr'?'Oui':'Yes'}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},1)">${lang==='ar'?'أحياناً':lang==='fr'?'Parfois':'Sometimes'}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},0)">${lang==='ar'?'لا':lang==='fr'?'Non':'No'}</button></div></div>`).join('')+`<button class="quiz-submit" onclick="submitQuiz()">${t.submitQuiz}</button>`;document.getElementById('quizResult').classList.add('hidden');window._quizAnswers={};}
function selectQuizOpt(qi,v){window._quizAnswers[qi]=v;document.querySelectorAll(`#quiz-q-${qi} .quiz-opt`).forEach((o,oi)=>o.classList.toggle('selected',[2,1,0][oi]===v));playSound('click');}
function submitQuiz(){const a=window._quizAnswers||{};if(Object.keys(a).length<QUIZ.length){showToast(lang==='ar'?'أجب على جميع الأسئلة':'Answer all');return;}const inv=[1,4];let score=0;Object.entries(a).forEach(([qi,v])=>{score+=inv.includes(parseInt(qi))?(2-v):v;});const max=QUIZ.length*2;const pct=Math.round(score/max*100);let emoji,title,desc;if(pct>=75){emoji='🛡️';title=lang==='ar'?'مدافع قوي!':'Strong defender!';desc=lang==='ar'?'معرفتك ممتازة — واصل التعلم والدفاع بالحكمة':'Your knowledge is excellent — keep learning and defending with wisdom';}else if(pct>=50){emoji='📖';title=lang==='ar'?'جيد':'Good';desc=lang==='ar'?'معرفتك جيدة — واصل القراءة':'Your knowledge is good — keep reading';}else{emoji='🔍';title=lang==='ar'?'ابدأ التعلم!':'Start learning!';desc=lang==='ar'?'تحتاج قراءة أكثر عن الإسلام':'You need to read more about Islam';}const r=document.getElementById('quizResult');r.classList.remove('hidden');r.innerHTML=`<div class="qr-emoji">${emoji}</div><div class="qr-score">${pct}%</div><div class="qr-title">${title}</div><div class="qr-desc">${desc}</div><button class="quiz-submit" onclick="renderQuiz()" style="margin-top:16px">${T[lang].quizAgain}</button>`;r.scrollIntoView({behavior:'smooth'});playSound('success');}

function renderAbout(){const about={ar:{disclaimerTitle:'⚠️ تنبيه مهم',disclaimer:'لست عالماً ولا مفتياً. هذا جهد متواضع من مسلم يحب كتب الشيخ الغزالي. ليست فتوى.',authorName:'الشيخ محمد الغزالي',authorDates:'١٩١٧ — ١٩٩٦',authorBio:'عالم ومفكر إسلامي مصري، لُقب بـ"أديب الدعوة". ألّف أكثر من ٩٤ كتاباً.',bookTitle:'عن الكتاب',bookDesc:'كتاب "الإسلام المفترى عليه" يدافع فيه الشيخ الغزالي عن الإسلام ضد الاتهامات الباطلة التي يواجهها — من العنف وقمع المرأة إلى العداء للعلم والحرية. يقدم ردوداً علمية موثقة بالأدلة من القرآن والسنة والتاريخ.',sourcesTitle:'المصادر',sources:['كتاب "الإسلام المفترى عليه" — الشيخ محمد الغزالي','القرآن الكريم','صحيح البخاري ومسلم'],contact:'تواصل: abdelhak.bourdim@gmail.com'},en:{disclaimerTitle:'⚠️ Important Notice',disclaimer:'I am not a scholar. This is a humble effort by a Muslim who loves Sheikh al-Ghazali\'s books. Not a fatwa.',authorName:'Sheikh Mohammed al-Ghazali',authorDates:'1917 — 1996',authorBio:'Egyptian Islamic scholar and thinker. Author of 94+ books.',bookTitle:'About the Book',bookDesc:'"Islam Falsely Accused" defends Islam against false accusations — from violence and women\'s oppression to hostility toward science and freedom. It provides evidence-based scholarly responses.',sourcesTitle:'Sources',sources:['"Islam Falsely Accused" — Sheikh Mohammed al-Ghazali','The Holy Quran','Sahih al-Bukhari and Muslim'],contact:'Contact: abdelhak.bourdim@gmail.com'},fr:{disclaimerTitle:'⚠️ Avis Important',disclaimer:'Je ne suis ni savant ni mufti. C\'est un effort humble. Ce n\'est pas une fatwa.',authorName:'Sheikh Mohammed al-Ghazali',authorDates:'1917 — 1996',authorBio:'Savant et penseur islamique \u00e9gyptien. Auteur de plus de 94 livres.',bookTitle:'\u00c0 Propos du Livre',bookDesc:'\u00ab L\'Islam Faussement Accus\u00e9 \u00bb d\u00e9fend l\'Islam contre les fausses accusations avec des r\u00e9ponses savantes fond\u00e9es sur des preuves.',sourcesTitle:'Sources',sources:['\u00ab L\'Islam Faussement Accus\u00e9 \u00bb — Sheikh al-Ghazali','Le Saint Coran','Sahih al-Bukhari et Muslim'],contact:'Contact : abdelhak.bourdim@gmail.com'}};const a=about[lang];document.getElementById('aboutContainer').innerHTML=`<div class="about-disclaimer"><div class="about-disclaimer-title">${a.disclaimerTitle}</div><p>${a.disclaimer}</p></div><div class="about-author"><span class="about-author-icon">📚</span><div class="about-author-info"><div class="about-author-name">${a.authorName}</div><div class="about-author-dates">${a.authorDates}</div><div class="about-author-bio">${a.authorBio}</div></div></div><div class="about-section"><div class="about-section-title">${a.bookTitle}</div><p class="about-text">${a.bookDesc}</p></div><div class="about-section"><div class="about-section-title">${a.sourcesTitle}</div>${a.sources.map(s=>`<p class="about-text">&#8226; ${s}</p>`).join('')}</div><div class="about-section"><p class="about-text">${a.contact}</p></div>`;}

function renderHelp(){const h={ar:[{title:'⚠️ تنبيه',body:'لست عالماً. هذا جهد متواضع.'},{title:'📚 المصادر',body:'كتاب "الإسلام المفترى عليه" للشيخ محمد الغزالي.'},{title:'✨ المميزات',body:'ثلاث لغات، ٣ أنماط، ٢٠ بطاقة، خط دفاع، عادات، اختبار، أدعية.'}],en:[{title:'⚠️ Disclaimer',body:'I am not a scholar. This is a humble effort.'},{title:'📚 Sources',body:'"Islam Falsely Accused" by Sheikh al-Ghazali.'},{title:'✨ Features',body:'Three languages, 3 themes, 20 cards, defense line, habits, quiz, duas.'}],fr:[{title:'⚠️ Avertissement',body:'Je ne suis pas un savant.'},{title:'📚 Sources',body:'\u00ab L\'Islam Faussement Accus\u00e9 \u00bb par Sheikh al-Ghazali.'},{title:'✨ Fonctionnalit\u00e9s',body:'Trois langues, 3 th\u00e8mes, 20 cartes, d\u00e9fense, habitudes, quiz, duas.'}]};document.getElementById('helpBody').innerHTML=h[lang].map(i=>`<div class="help-item"><div class="help-item-title">${i.title}</div><div>${i.body}</div></div>`).join('');}

function renderDuas(){document.getElementById('duaPanelContent').innerHTML=DUAS.map(d=>{const dd=d[lang];return`<div class="dua-item"><div class="dua-item-label">${dd.label}</div><div class="dua-item-ar">${dd.text}</div><div class="dua-item-tr">${dd.tr}</div></div>`;}).join('');}

function initScrollReveal(){if(!('IntersectionObserver' in window))return;const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');obs.unobserve(e.target);}});},{threshold:0.08,rootMargin:'0px 0px -40px 0px'});function oa(){document.querySelectorAll('.scroll-reveal:not(.revealed)').forEach(el=>obs.observe(el));}oa();document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>setTimeout(oa,100)));}

function initKeyboardNav(){document.addEventListener('keydown',e=>{if(e.key==='Escape'){const hp=document.getElementById('helpPanel');if(!hp.classList.contains('hidden')){toggleHelp();return;}const dp=document.getElementById('duaPanel');if(!dp.classList.contains('hidden')){toggleDuaPanel();return;}document.querySelectorAll('.principle-card.open').forEach(c=>c.classList.remove('open'));}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){const cp=document.getElementById('panel-cards');if(!cp||!cp.classList.contains('active'))return;e.preventDefault();const cards=Array.from(document.querySelectorAll('.principle-card')).filter(c=>c.style.display!=='none');if(!cards.length)return;if(currentCardIdx>=0&&currentCardIdx<cards.length)cards[currentCardIdx].classList.remove('open');const dir=(document.documentElement.dir==='rtl')?(e.key==='ArrowRight'?-1:1):(e.key==='ArrowRight'?1:-1);currentCardIdx=Math.max(0,Math.min(cards.length-1,currentCardIdx+dir));cards[currentCardIdx].classList.add('open');cards[currentCardIdx].scrollIntoView({behavior:'smooth',block:'center'});playSound('click');}});}

function toggleCard(id){const c=document.getElementById(id);if(c){c.classList.toggle('open');playSound('click');}}
function toggleHelp(){document.getElementById('helpPanel').classList.toggle('hidden');playSound('click');}
function toggleDuaPanel(){document.getElementById('duaPanel').classList.toggle('hidden');playSound('click');}
function showToast(msg){const t=document.getElementById('toast'),m=document.getElementById('toastMsg');if(t&&m){m.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2500);}}
function initScrollTop(){const btn=document.getElementById('scrollTop');window.addEventListener('scroll',()=>{if(btn)btn.classList.toggle('visible',window.scrollY>300);});}
const AudioCtx=window.AudioContext||window.webkitAudioContext;let audioCtx;
function playSound(type){try{if(!audioCtx)audioCtx=new AudioCtx();const osc=audioCtx.createOscillator();const gain=audioCtx.createGain();osc.connect(gain);gain.connect(audioCtx.destination);gain.gain.value=0.06;if(type==='click'){osc.frequency.value=800;osc.type='sine';gain.gain.value=0.04;}else if(type==='success'){osc.frequency.value=523;osc.type='sine';}else if(type==='theme'){osc.frequency.value=440;osc.type='triangle';gain.gain.value=0.05;}osc.start();osc.stop(audioCtx.currentTime+0.1);}catch(e){}}

(function(){let sx=0,sy=0;const to=['home','cards','defense','habits','quiz','about'];document.addEventListener('touchstart',e=>{sx=e.changedTouches[0].screenX;sy=e.changedTouches[0].screenY;},{passive:true});document.addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-sx;const dy=e.changedTouches[0].screenY-sy;if(Math.abs(dx)<80||Math.abs(dy)>Math.abs(dx)*0.7)return;const ct=document.querySelector('.tab.active');if(!ct)return;const ci=to.indexOf(ct.dataset.tab);if(ci<0)return;const isRTL=document.documentElement.dir==='rtl';let ni;if(dx>0)ni=isRTL?Math.min(ci+1,to.length-1):Math.max(ci-1,0);else ni=isRTL?Math.max(ci-1,0):Math.min(ci+1,to.length-1);if(ni!==ci)document.querySelector(`.tab[data-tab="${to[ni]}"]`).click();},{passive:true});})();
